### ISSUE TITLE
Question: is supposed to work?

### ISSUE THREAD

**Issue by xenogenesi** [e1dr1tch/Skeletal_Animation#1]
Hi, thanks for sharing, I can compile and run TrueGL, it open a window an print some log in the terminal, it doesn't crash, but the window only show a dark gray flat background.

My guess so far is that some gl stuff is failing and the errors are ignored, but before looking into it I'd like to confirm it should work and display the animated model.

Thanks!

**Comment by Arvolear** [comment]
Hello, thanks for your comment. Could you please describe the problem in more detail?

**Comment by xenogenesi** [comment]
Hello @e1dr1tch , thanks to you for replying, `opengl/TrueGL` compile and link correctly (I had to define `-DGLM_ENABLE_EXPERIMENTAL` to get it to compile), I can run it, that's the shell ouput:

    % ./opengl/TrueGL
    Compiling shader : /home/alex/src/Skeletal_Animation/opengl/vertexShader.glsl
    Compiling shader : /home/alex/src/Skeletal_Animation/opengl/fragmentShader.glsl
    Linking program
    NO PARENT BONE FOR Bone
    NO PARENT BONE FOR Bone.007
    Texture type: texture_diffuse

it open the new window correctly, but the window show nothing, just a flat dark gray background color, no 3d models, I'd like to know if it is supposed to work, show something, do you get a 3d model/scene, animated?

My build environment is a Debian/sid, gcc-8.3 (g++ 8.30), glxinfo output:
OpenGL renderer string: GeForce GTX 690/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 418.74
OpenGL core profile shading language version string: 4.60 NVIDIA

I added an assert after every `gl*` call but without success, the behavior remain the same:

    assert(glGetError() == 0);

**Comment by Arvolear** [comment]
Thank you. Yes, it is supposed to run correctly. I have added floor to the program to exclude the chances of you simply being lost in the grey window. Have you tried to move the mouse or press WASD keys? Actually the preview is interactive. 

There are no errors in the output so the model loads correctly, you just can't see it. It is not the shader otherwise the screen would be black (not grey). So they are libs. Have you installed all the libs correctly [README](https://github.com/e1dr1tch/Skeletal_Animation/blob/master/README.md)?

The code runs exactly as it supposed to run on my machine. What kind of errors you get when compile without `-DGLM_ENABLE_EXPERIMENTAL`?

**Comment by xenogenesi** [comment]
>  I have added floor to the program to exclude the chances of you simply being lost in the grey window

I see it, a textured floor within a circle, I can use WASD to move the camera, if I try the mouse it move the view but seems a bit glitchy

> Have you installed all the libs correctly README?

    libsoil-dev          1.07~20080707.dfsg-4
    libglfw3-dev:amd64   3.2.1-1
    libassimp-dev:amd64  4.1.0~dfsg-5
    libglm-dev           0.9.9.3-2

(note: glm is not mentioned in the readme)

> What kind of errors you get when compile without -DGLM_ENABLE_EXPERIMENTAL?

I paste only one but obviously I get one for each include

    In file included from bone.hpp:13,
                     from bone.cpp:5:
    /usr/include/glm/gtx/transform.hpp:23:3: error: #error "GLM: GLM_GTX_transform is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
    # error "GLM: GLM_GTX_transform is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."


About the mesa, the libGL linked is installed by the package libgl1 (Vendor neutral GL dispatch library), I can't find it (is a symbolic links nightmare) but I guess somewhere down the nvidia driver provide the hw accelerated implementation.

`% dpkg -S /usr/lib/x86_64-linux-gnu/libGL.so.1`

    diversion by glx-diversions from: /usr/lib/x86_64-linux-gnu/libGL.so.1
    diversion by glx-diversions to: /usr/lib/mesa-diverted/x86_64-linux-gnu/libGL.so.1
    libgl1:amd64: /usr/lib/x86_64-linux-gnu/libGL.so.1

below the list of all the linked libraries

`ldd opengl/TrueGL`:

	linux-vdso.so.1 (0x00007ffd709ea000)
	libassimp.so.4 => /usr/lib/x86_64-linux-gnu/libassimp.so.4 (0x00007f4a8ca3b000)
	libglfw.so.3 => /usr/lib/x86_64-linux-gnu/libglfw.so.3 (0x00007f4a8c81e000)
	libGLEW.so.2.1 => /usr/lib/x86_64-linux-gnu/libGLEW.so.2.1 (0x00007f4a8c772000)
	libSOIL.so.1 => /usr/lib/libSOIL.so.1 (0x00007f4a8c55b000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f4a8c4c7000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4a8c344000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4a8c1bf000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4a8c1a5000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4a8bfe4000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f4a8bdc6000)
	libminizip.so.1 => /usr/lib/x86_64-linux-gnu/libminizip.so.1 (0x00007f4a8bbba000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f4a8bbb0000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4a8bba9000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f4a8ba68000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4a8ba47000)
	libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007f4a8b83c000)
	libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007f4a8b837000)
	libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007f4a8b631000)
	libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007f4a8b622000)
	libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007f4a8b5ee000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007f4a8b531000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4a8d25a000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f4a8b507000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f4a8b2f5000)
	libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f4a8b0e9000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f4a8aee3000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f4a8acdf000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f4a8aad9000)
	libbsd.so.0 => /usr/lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f4a8aabf000)

**Comment by xenogenesi** [comment]
Here, should be all of them

    In file included from /usr/include/glm/gtx/string_cast.hpp:23,
                     from skeleton.hpp:14,
                     from gameobject.cpp:5:
    /usr/include/glm/gtx/dual_quaternion.hpp:24:3: error: #error "GLM: GLM_GTX_dual_quaternion is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
     # error "GLM: GLM_GTX_dual_quaternion is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
       ^~~~~
    In file included from skeleton.hpp:14,
                     from gameobject.cpp:5:
    /usr/include/glm/gtx/string_cast.hpp:28:3: error: #error "GLM: GLM_GTX_string_cast is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
     # error "GLM: GLM_GTX_string_cast is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
       ^~~~~
    In file included from gameobject.hpp:8,
                     from gameobject.cpp:7:
    /usr/include/glm/gtx/matrix_decompose.hpp:24:3: error: #error "GLM: GLM_GTX_matrix_decompose is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."
     # error "GLM: GLM_GTX_matrix_decompose is an experimental extension and may change in the future. Use #define GLM_ENABLE_EXPERIMENTAL before including it, if you really want to use it."

**edit**

Probably something is not working with these, tomorrow I will try it on another PC, thanks for the support in the meantime

**Comment by Arvolear** [comment]
I found out that you are running different libs versions. I will install new onces asap and let you know. I think it is assimp 4.1 which loads .fbx models slightly differently.

**Comment by Arvolear** [comment]
The problem lays in glm. I have run the code with new glm version starting from 0.9.9.0 and got dark-grey window without any models. Please try installing [this version](https://github.com/g-truc/glm/releases/tag/0.9.8.5) and recompiling everything.

**Comment by xenogenesi** [comment]
Thank you! That was it, it works

**Comment by Arvolear** [comment]
That's great!
