### ISSUE TITLE
Unable to get the expected result. Could you please help

### ISSUE THREAD

**Issue by rahul-deshmane** [e1dr1tch/Skeletal_Animation#2]
![image](https://user-images.githubusercontent.com/45894717/74561577-d83c4400-4f8e-11ea-97cd-9e2ac4aca2dc.png)

**Comment by Arvolear** [comment]
Hi, could you please check and share the libraries versions you use? The problem may lie in them. 
Please have a look at [this](https://github.com/e1dr1tch/Skeletal_Animation/issues/1) topic, this might help.

**Comment by Arvolear** [comment]
I see you are running VS on Windows, but originally the code was written under Linux and hasn't been tested for compatibility. There might occur obvious problems with "file pathes" and less obvious libraries errors. 
Could you please tell me more about your environment?

**Comment by rahul-deshmane** [comment]
Yes I am working on windows and using GLEW instead of GLEWStatic lib.
The caterpillar model is getting loaded successfully with ASSIMP, as I can
see all the meshes,bones and animations in the scene data structure.

I have a query :If I comment out the call to skeleton update, will the
model just be loaded in bind pose and will not do any animation?

Thanks

**Comment by Arvolear** [comment]
Actually it is much simpler. Just comment out the line 158 ([here](https://github.com/e1dr1tch/Skeletal_Animation/blob/master/opengl/graphics.cpp)). The animation will no longer start.

But still, please leave here your exact library versions + console output. 

There are 2 gameobjects in the scene: animated caterpillar and static floor. The problem also may stem from .fbx caterpillar's file extension (weird Assimp behavior). But you should see the floor.

Correct console output:
![image](https://user-images.githubusercontent.com/47551140/74590277-acb06c80-5015-11ea-8310-cdf69d59d41c.png)
